[package]
name = "stanley-rs"
version = "0.1.0"
authors = ["Clark Kampfe <clark.kampfe@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.11"
glob = "0.3.0"
minifier = "0.0.36"
nom = "5.1.2"
pulldown-cmark = { version = "0.7.2", default-features = false, features = ["simd"] }
rss = "1.9.0"
tera = "1.3.1"

[profile.release]
opt-level = 3
lto = true
debug = false
codegen-units = 1
