[package]
name = "stanley-rs"
version = "0.1.0"
authors = ["Clark Kampfe <clark.kampfe@gmail.com>"]
edition = "2018"

[dependencies]
glob = "0.3"
nom = "4.2"
pulldown-cmark = "0.5"
rss = "1.7"
serde = "1.0"
tera = "1.0.0-beta.4"
time = "0.1"

[profile.release]
opt-level = 3
lto = true
debug = false
codegen-units = 1
