[package]
name = "stanley-rs"
version = "0.1.0"
authors = ["Clark Kampfe <clark.kampfe@gmail.com>"]
edition = "2018"

[dependencies]
glob = "0.3"
minifier = "0"
nom = "5.1"
pulldown-cmark = { version = "0.7", default-features = false, features = ["simd"] }
rss = "1.9"
tera = "1.1"
time = "0.2.9"

[profile.release]
opt-level = 3
lto = true
debug = false
codegen-units = 1
