[package]
name = "stanley-rs"
version = "0.1.0"
authors = ["Clark Kampfe <clark.kampfe@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
glob = "0.3"
minifier = "0.0.36"
nom = "6.1"
pulldown-cmark = { version = "0.8", default-features = false, features = ["simd"] }
rss = "1.10"
tera = { version = "1.9", default-features = false }

[profile.release]
codegen-units = 1
lto = true
