[package]
name = "stanley-rs"
version = "0.1.0"
authors = ["Clark Kampfe <clark.kampfe@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
chrono = "0.4"
glob = "0.3"
nom = "7.1"
pulldown-cmark = { version = "0.9", default-features = false, features = ["simd"] }
rss = "2.0"
tera = { version = "1.15", default-features = false }

[profile.release]
codegen-units = 1
lto = true
